// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FitnessModellDBI.Models
{
    [Table("Membership")]
    public partial class Membership
    {
        public Membership()
        {
            Users = new HashSet<User>();
        }

        [Key]
        public int Id { get; set; }
        [Column(TypeName = "date")]
        public DateTime DateOfPurchase { get; set; }
        [Column(TypeName = "date")]
        public DateTime DateOfExpiry { get; set; }
        public double Price { get; set; }

        [InverseProperty("Membership")]
        public virtual ICollection<User> Users { get; set; }
    }
}