// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FitnessModellDBI.Models
{
    [Table("Trainer")]
    [Index("PhoneNumber", Name = "UQ__Trainer__85FB4E38C9E4C834", IsUnique = true)]
    public partial class Trainer
    {
        public Trainer()
        {
            Users = new HashSet<User>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(255)]
        [Unicode(false)]
        public string Name { get; set; }
        [Required]
        [StringLength(16)]
        [Unicode(false)]
        public string PhoneNumber { get; set; }
        [Required]
        [StringLength(255)]
        [Unicode(false)]
        public string Description { get; set; }

        [InverseProperty("Trainer")]
        public virtual ICollection<User> Users { get; set; }
    }
}