// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FitnessModellDBI.Models
{
    [Table("User")]
    [Index("PhoneNumber", Name = "UQ__User__85FB4E3887E8E6B0", IsUnique = true)]
    public partial class User
    {
        public User()
        {
            Workouts = new HashSet<Workout>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(255)]
        [Unicode(false)]
        public string Name { get; set; }
        [Required]
        [StringLength(16)]
        [Unicode(false)]
        public string PhoneNumber { get; set; }
        public int TrainerId { get; set; }
        public int MembershipId { get; set; }

        [ForeignKey("MembershipId")]
        [InverseProperty("Users")]
        public virtual Membership Membership { get; set; }
        [ForeignKey("TrainerId")]
        [InverseProperty("Users")]
        public virtual Trainer Trainer { get; set; }

        [ForeignKey("UserId")]
        [InverseProperty("Users")]
        public virtual ICollection<Workout> Workouts { get; set; }
    }
}