// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FitnessModellDBI.Models
{
    [Table("Workout")]
    public partial class Workout
    {
        public Workout()
        {
            Users = new HashSet<User>();
        }

        [Key]
        public int Id { get; set; }
        public int NumOfExercises { get; set; }
        [Required]
        [StringLength(10)]
        [Unicode(false)]
        public string WorkoutDuration { get; set; }
        public int ExercisesId { get; set; }
        [StringLength(255)]
        [Unicode(false)]
        public string Description { get; set; }

        [ForeignKey("ExercisesId")]
        [InverseProperty("Workouts")]
        public virtual Exercise Exercises { get; set; }

        [ForeignKey("WorkoutId")]
        [InverseProperty("Workouts")]
        public virtual ICollection<User> Users { get; set; }
    }
}